language: php
php:
  - '7.1'
install:
  - composer require squizlabs/php_codesniffer
script:
  - vendor/bin/phpcs --standard=PSR2 src/AppBundle/
  - deploy.sh
notifications:
  email:
    - aurelien@wildcodeschool.fr
